version: '3.7'

services:

  posgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - '10000:5432'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_PORT: 5432
    volumes:
      - postgres-db-vol:/var/lib/postgres/data

volumes:
  postgres-db-vol:
